import type { StratagemDefinition } from './types'

/** Fictional development data. Faction rules should be supplied by data modules later. */
export const SAMPLE_STRATAGEMS: readonly StratagemDefinition[] = [
  {
    id: 'coordinated-volley',
    kind: 'STRATAGEM',
    name: 'Coordinated Volley',
    description: 'A firing-line coordination option used to exercise active-player timing.',
    cpCost: 1,
    ownerScope: 'ACTIVE_PLAYER',
    timing: 'At the start of your Shooting phase.',
    phases: ['SHOOTING'],
    triggers: ['PHASE_START'],
    reaction: false,
    usageLimits: ['ONCE_PER_PHASE'],
    source: 'Development sample',
  },
  {
    id: 'prismatic-screen',
    kind: 'STRATAGEM',
    name: 'Prismatic Screen',
    description: 'A defensive response used to exercise targeted-unit reaction timing.',
    cpCost: 1,
    ownerScope: 'OPPONENT',
    timing: 'When one of your units is selected as a target.',
    phases: ['SHOOTING'],
    triggers: ['UNIT_SELECTED_AS_TARGET'],
    reaction: true,
    usageLimits: ['ONCE_PER_PHASE'],
    source: 'Development sample',
  },
  {
    id: 'intercepting-feint',
    kind: 'STRATAGEM',
    name: 'Intercepting Feint',
    description: 'A defensive response used to exercise charge declaration timing.',
    cpCost: 1,
    ownerScope: 'OPPONENT',
    timing: 'When an enemy unit declares a charge.',
    phases: ['CHARGE'],
    triggers: ['CHARGE_DECLARED'],
    reaction: true,
    usageLimits: ['ONCE_PER_TURN'],
    source: 'Development sample',
  },
  {
    id: 'duelist-overdrive',
    kind: 'STRATAGEM',
    name: 'Duelist Overdrive',
    description: 'A melee option used to exercise active-player Fight phase timing.',
    cpCost: 2,
    ownerScope: 'ACTIVE_PLAYER',
    timing: 'At the start of your Fight phase.',
    phases: ['FIGHT'],
    triggers: ['PHASE_START'],
    reaction: false,
    usageLimits: ['ONCE_PER_TURN'],
    source: 'Development sample',
  },
  {
    id: 'last-reserve-signal',
    kind: 'STRATAGEM',
    name: 'Last Reserve Signal',
    description: 'A broad one-use response used to exercise explicit reaction holds.',
    cpCost: 1,
    ownerScope: 'OPPONENT',
    timing: 'When a relevant action is confirmed.',
    phases: ['ANY'],
    triggers: ['CUSTOM_CONFIRMATION'],
    reaction: true,
    usageLimits: ['ONCE_PER_BATTLE'],
    source: 'Development sample',
  },
]

export function sampleStratagemsByPlayer(playerIds: readonly string[]): Record<string, readonly StratagemDefinition[]> {
  return Object.fromEntries(playerIds.map((playerId) => [playerId, SAMPLE_STRATAGEMS]))
}
