import type { OfficialSecondaryId, SecondaryDefinition } from './secondaryTypes'

export type OfficialTiming = 'own' | 'opponent' | 'either'
export type OfficialSecondaryDefinition = SecondaryDefinition & {
  id: OfficialSecondaryId
  scoreAt: OfficialTiming
  fixed?: boolean
  /** Tactical-only replacement. Defend Stronghold must be replaced in round one. */
  redraw?: 'optional' | 'round-one-optional' | 'round-one-required' | 'no-target' | 'cleanse-conflict' | 'plunder-conflict'
  /** A card with a variable award offers these values when the condition is met. */
  awards: readonly number[]
}

const definitions: OfficialSecondaryDefinition[] = [
  { id: 'OFFICIAL_A_GRIEVOUS_BLOW', name: 'A Grievous Blow', vp: 5, category: 'ELIMINATION', description: 'Tactical: 5 VP if one or more enemy units with Starting Strength 13+ were destroyed this turn. Fixed: 4 VP for each such unit destroyed this turn. If no eligible target exists when drawn, you may replace this card.', timing: ['END_TURN', 'ON_DRAW'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', fixed: true, redraw: 'no-target', awards: [5] },
  { id: 'OFFICIAL_A_TEMPTING_TARGET', name: 'A Tempting Target', vp: 5, category: 'OBJECTIVE', description: 'When drawn, your opponent selects an objective in No Man’s Land that is not their home objective. Score 5 VP if you control the selected objective at the end of your turn.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'TARGET_SELECTION', scoreAt: 'own', awards: [5] },
  { id: 'OFFICIAL_ASSASSINATION', name: 'Assassination', vp: 5, category: 'ELIMINATION', description: 'Tactical: 5 VP if an enemy CHARACTER model was destroyed this turn, or if all enemy CHARACTER models in the battle have been destroyed. Fixed: 3 VP per enemy CHARACTER model destroyed this turn, plus 1 VP for each of those models with Wounds 4+.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', fixed: true, awards: [5] },
  { id: 'OFFICIAL_BEACON', name: 'Beacon', vp: 5, category: 'POSITION', description: 'When drawn, choose one of your units on the battlefield or embarked within a TRANSPORT there. At the end of an opponent’s turn (or the end of round 5), score 3 VP if that unit is on the battlefield outside your deployment zone, or 5 VP if outside your territory.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'opponent', awards: [3, 5] },
  { id: 'OFFICIAL_BEHIND_ENEMY_LINES', name: 'Behind Enemy Lines', vp: 5, category: 'POSITION', description: 'At the end of your turn score 3 VP per unit wholly within your opponent’s deployment zone, up to 5 VP. AIRCRAFT and Battle-shocked units do not count. In round 1 you may replace this card when drawn.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', redraw: 'round-one-optional', awards: [3, 5] },
  { id: 'OFFICIAL_BRING_IT_DOWN', name: 'Bring It Down', vp: 5, category: 'ELIMINATION', description: 'Tactical: 5 VP if an enemy model with Wounds 10+ was destroyed this turn. Fixed: 4 VP per such model destroyed this turn. If there is no eligible target when drawn, you may replace this card.', timing: ['END_TURN', 'ON_DRAW'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', fixed: true, redraw: 'no-target', awards: [5] },
  { id: 'OFFICIAL_BURDEN_OF_TRUST', name: 'Burden of Trust', vp: 5, category: 'OBJECTIVE', description: 'When drawn or at the start of your turn, assign one of your units to guard each objective you control. At the end of an opponent’s turn (or round 5), score 2 VP per objective you still control with its assigned unit in range, up to 5 VP.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'opponent', awards: [2, 4, 5] },
  { id: 'OFFICIAL_CENTRE_GROUND', name: 'Centre Ground', vp: 5, category: 'POSITION', description: 'At the end of your turn, have a unit within 3″ of the battlefield centre (excluding AIRCRAFT and Battle-shocked units) and no enemy unit within 3″: 3 VP. Score 5 VP if no enemy is within 6″.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', awards: [3, 5] },
  { id: 'OFFICIAL_CLEANSE', name: 'Cleanse', vp: 5, category: 'MISSION_ACTION', description: 'In your Shooting phase, start Cleanse with one unit in range of a non-home objective; each unit must choose a different objective. The action completes at the end of your turn if that unit controls its objective. Score 2 VP for one completed Cleanse or 5 VP for two or more. If Plunder is active when drawn, you may replace this card.', timing: ['MISSION_ACTION', 'END_TURN', 'ON_DRAW'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', redraw: 'plunder-conflict', awards: [2, 5] },
  { id: 'OFFICIAL_DEFEND_STRONGHOLD', name: 'Defend Stronghold', vp: 5, category: 'OBJECTIVE', description: 'From round 2, at the end of an opponent’s turn (or the end of round 5), score 3 VP if you control your home objective, plus 2 VP if no enemy unit is in your deployment zone. Replace this card when drawn in round 1.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'opponent', redraw: 'round-one-required', awards: [3, 5] },
  { id: 'OFFICIAL_DISPLAY_OF_MIGHT', name: 'Display of Might', vp: 5, category: 'POSITION', description: 'Have more of your units than enemy units wholly within No Man’s Land, excluding AIRCRAFT and Battle-shocked units. At the end of your turn score 2 VP; at the end of an opponent’s turn score 5 VP.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', awards: [2, 5] },
  { id: 'OFFICIAL_ENGAGE_ON_ALL_FRONTS', name: 'Engage on All Fronts', vp: 5, category: 'POSITION', description: 'At the end of your turn have qualifying units wholly in three or four battlefield quarters, more than 6″ from the centre. AIRCRAFT and Battle-shocked units do not count. Tactical: 3/5 VP for three/four quarters. Fixed: 2/4 VP.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', fixed: true, awards: [3, 5] },
  { id: 'OFFICIAL_FORWARD_POSITION', name: 'Forward Position', vp: 5, category: 'OBJECTIVE', description: 'At the end of your turn score 5 VP if you control the opponent’s home objective and/or every expansion objective. In round 1 you may replace this card when drawn.', timing: ['ON_DRAW', 'END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', redraw: 'round-one-optional', awards: [5] },
  { id: 'OFFICIAL_NO_PRISONERS', name: 'No Prisoners', vp: 5, category: 'ELIMINATION', description: 'At the end of either player’s turn, score 2 VP for each enemy unit destroyed during that turn, up to 5 VP.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', awards: [2, 4, 5] },
  { id: 'OFFICIAL_OUTFLANK', name: 'Outflank', vp: 5, category: 'POSITION', description: 'At the end of your turn, score 3 VP if one of your units is within 6″ of a battlefield edge outside your territory. Score 5 VP if two units are near opposite parallel edges and at least one is outside your territory. AIRCRAFT and Battle-shocked units do not count.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', awards: [3, 5] },
  { id: 'OFFICIAL_OVERWHELMING_FORCE', name: 'Overwhelming Force', vp: 5, category: 'ELIMINATION', description: 'At the end of either player’s turn, score 3 VP for each enemy unit destroyed this turn that began the turn in range of an objective, up to 5 VP.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'either', awards: [3, 5] },
  { id: 'OFFICIAL_PLUNDER', name: 'Plunder', vp: 5, category: 'MISSION_ACTION', description: 'In your Shooting phase, start Plunder with one unit within a terrain area outside your territory (one unit per turn). The action completes immediately; score 5 VP at the end of your turn. If Cleanse is active when drawn, you may replace this card.', timing: ['MISSION_ACTION', 'END_TURN', 'ON_DRAW'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', redraw: 'cleanse-conflict', awards: [5] },
  { id: 'OFFICIAL_SECURE_NO_MANS_LAND', name: 'Secure No Man’s Land', vp: 5, category: 'OBJECTIVE', description: 'At the end of your turn, score 5 VP if you control at least two objectives in No Man’s Land that are not home objectives.', timing: ['END_TURN'], evaluationMode: 'REQUIRES_CONFIRMATION', scoreAt: 'own', awards: [5] },
]

export const OFFICIAL_SECONDARY_DEFINITIONS = Object.freeze(definitions.map((definition) => Object.freeze(definition)))
export const OFFICIAL_SECONDARY_IDS = Object.freeze(OFFICIAL_SECONDARY_DEFINITIONS.map((definition) => definition.id))
export const OFFICIAL_FIXED_IDS = Object.freeze(OFFICIAL_SECONDARY_DEFINITIONS.filter((definition) => definition.fixed).map((definition) => definition.id))
export const OFFICIAL_SECONDARY_BY_ID = Object.freeze(Object.fromEntries(OFFICIAL_SECONDARY_DEFINITIONS.map((definition) => [definition.id, definition])) as Record<OfficialSecondaryId, OfficialSecondaryDefinition>)
